### ISSUE TITLE
check_vg_size

### ISSUE THREAD

**Issue by Care4servers** [billcarlson/check_vg_size#10]
Hi,

We are having some issue on getting vgs values on the master node.

```
/usr/local/nagios/libexec/check_nrpe -H xxx.xxx.xxx.xx -c check_vg_size
false
No Volumegroup wasn't valid or wasn't found
```
In nagios client it is working.

```
# ./check_vg_size -w 50 -c 20  -a
VG VolGroup WARNING Available space is 42 GB;| VolGroup=42GB;50;20;0;930
```

Please any one help me to resolve it.

**Comment by jwerak** [comment]
This is not issue with this script - you demonstrated that it is working properly on your server. 

The issue is most likely due to lack of privileges of user triggering check_nrpe. 
You should be able to run 

```
sudo /usr/local/nagios/libexec/check_nrpe -H xxx.xxx.xxx.xx -c check_vg_size
```

Here are some links that should help you out:
http://www.linuxquestions.org/questions/linux-newbie-8/need-help-with-sudo-and-etc-sudoers-767300/
https://kb.op5.com/display/HOWTOs/Running+plugins+with+NRPE+as+root+or+another+user

**Comment by Care4servers** [comment]
Hi,

I think you are missing the error here. it is able to process the command. But can't able to retrieve exact output.

When running on server nagios
```
# /usr/local/nagios/libexec/check_nrpe -H xxx.xxx.xx -c check_vg_size
false
No Volumegroup wasn't valid or wasn't found
```

Command specified on nrpe.conf

`command[check_vg_size]=/usr/local/nagios/libexec/check_vg_size  -w 50 -c 10 -a VolGroup`

But when running the same on localhost working.

```
agios]# /usr/local/nagios/libexec/check_vg -w 50 -c 10  -a VolGroup
VG VolGroup WARNING Available space is 42 GB;| VolGroup=42GB;50;10;0;930
```


It is not the issue with sudo. If there is a permission issue then the ouput would be like 
`NRPE: Unable to read output`

We are having KVM virtulizastion. So it is essential to monitor the vgs free space. Please show some shade on this issue. I can't find any other too to monitor the vgs effectively.

**Comment by jwerak** [comment]
so you've tried the settings 

```
command[check_vg_size]=/bin/sudo /usr/local/nagios/libexec/check_vg_size -w 50 -c 10 -a VolGroup
```

and it didn't work either?

**Comment by billcarlson** [comment]
The error message mentioned is from the plugin, not NRPE. The plugin reports information correctly back to NRPE, which again, is why no NRPE error is reported.

As jwerak and I have both noted, this plugin must be run as root, via sudo, to get the information needed.

To confirm why, get a shell as an unprivileged user and run the base command, 'vgs'. Note the output.

The actual problem is that LVM information is typically restricted to privileged accounts.

**Comment by Care4servers** [comment]
I have already tied the sudo but still facing same issue. Any other suggestion please,

**Comment by billcarlson** [comment]
Please get me the output of the following on target system:

- Output of command `vgs` ran as root account.
- Output of command `sudo /usr/local/nagios/libexec/check_vg_size -w 50 -c 10 -a VolGroup` ran as nrpe on target system. You may need to use /bin/bash for nrpe's shell: `su - nrpe -s /bin/bash`
This assumes your nrpe client is running as account nrpe.
- Output of `getenforce`.

**Comment by Care4servers** [comment]
Here is the ouput.

```
]# vgs                                                                 
  VG       #PV #LV #SN Attr   VSize   VFree                                               
  VolGroup   1  42   0 wz--n- 930.50g 42.79g 
```
```
~]# sudo /usr/local/nagios/libexec/check_vg_size -w 50 -c 10 -a VolGroup                                                                   
VG VolGroup WARNING Available space is 42 GB;| VolGroup=42GB;50;10;0;930  
```
           
I have allowed the nagios user on sudo userlist. Now it is working as below.
```
[nagios@hope67181hk ~]$ whoami
nagios
[nagios@hope67181hk ~]$ /usr/bin/sudo /usr/local/nagios/libexec/check_vg_size  -w 50 -c 10 -a VolGroup
VG VolGroup WARNING Available space is 42 GB;| VolGroup=42GB;50;10;0;930
```
nrpe.conf

`command[check_vg_size]=/usr/bin/sudo /usr/local/nagios/libexec/check_vg_size  -w 50 -c 10 -a VolGroup`

But still can't able get the output to master.

```
 ~]# /usr/local/nagios/libexec/check_nrpe -H 165.84.167.181 -c check_vg_size
NRPE: Unable to read output
```

**Comment by jwerak** [comment]
@Care4servers Would you provide output for @billcarlson 's 3 points? 

Main thing is to verify that 
- you know what user is used by nrpe (doesn't have to be nagios IIRC)
- is sudo set properly for such user? - Output of `sudo /usr/local/nagios/libexec/check_vg_size -w 50 -c 10 -a VolGroup`

**Comment by billcarlson** [comment]
You need to confirm the user account running nrpe. It varies, but I would guess in this case it runs as nrpe. `pgrep nrpe | xargs -r ps uww`

Also need output of `getenforce`. SELinux in enforce will also impact running the plugin via sudo.

**Comment by Care4servers** [comment]
Here is the output.

```
[root@hope67181hk ~]# pgrep nrpe | xargs -r ps uww
[root@hope67181hk ~]# getenforce
Disabled
```

thanks for assisting me on this issue.

**Comment by Care4servers** [comment]
I confirm that the nrpe is running with user name nagios.

**Comment by billcarlson** [comment]
Your check of nrpe process account actually says nrpe is not running.

**Comment by Care4servers** [comment]
Sorry for delay on getting back. nrpe is running fine on the server other plugins are working fine like check_ping , check_disk
