### ISSUE TITLE
Incorrect failure when run without permissions

### ISSUE THREAD

**Issue by flickerfly** [billcarlson/check_vg_size#11]
When this script is run by a user without permissions to run vgs, the script silently swallows the error and reports "No Volumegroup wasn't valid or wasn't found". This is because line 116 can't handle the error and so incorrectly outputs no results, causing $found to remain false and triggering the following if statement. 

```
$ vgs
  WARNING: Running as a non-root user. Functionality may be unavailable.
  /dev/mapper/control: open failed: Permission denied
  Failure to communicate with kernel device-mapper driver.
  Incompatible libdevmapper (unknown version) and kernel driver (unknown version).
$ sudo vgs
  VG               #PV #LV #SN Attr   VSize   VFree
  VG_Name   1   3   0 wz--n- 404.48g 374.41g
```

**Comment by flickerfly** [comment]
I added this right below the for loop. It appears to be more clear about the problem. 
```
        if [[ $($_vgs 2>&1|grep "Permission denied"|wc -l) -ge 1 ]]; then
                echo "Permission denied"
                exit $STATE_UNKNOWN
        fi
```

**Comment by billcarlson** [comment]
Thanks,. I will address sometime after tax season.
