### ISSUE TITLE
if [ $freespace -le $critspace ] -> -le accept only integers

### ISSUE THREAD

**Issue by vinc-g** [billcarlson/check_vg_size#3]
See this
http://www.linuxquestions.org/questions/programming-9/convert-float-to-integer-in-bash-468503/

the output of /sbin/vgs on my Debian Wheezy is : 
  VG       #PV #LV #SN Attr   VSize   VFree
  vg0        1   3   0 wz--n-  58,50g 7,37g

$freespace = "7,37" is not compatible with "-le"

For my particular need, i manage to make it work by changing the sed syntax : 
freespace=$($_vgs 2>/dev/null | grep $volumeName | awk -v n=$cnFree '{print $n}' | sed -e 's/\,.*//');

Regards
Here are the modifications I made : 
- the for-loops in order to increment the volumeGroups[$i] according (before, for each iteration the variable was filled with all vgs)
- the sed to truncate the free/full space value to an integer

http://pastebin.com/YLLKbSgi

<pre><code>
102,103c102,103
&lt;       for (( i=1; i &lt;= novg; i++)); do
&lt;               volumeGroups[$i]=$($_vgs | tail -n $i | awk '{print $1}' | head -n1)
---
&gt;       for (( i=0; i &lt; novg; i++)); do
&gt;               volumeGroups[$i]=$($_vgs | tail -n $novg | awk '{print $1}')
143,144c142,143
&lt;       freespace=$($_vgs 2&gt;/dev/null | grep $volumeName | awk -v n=$cnFree '{print $n}' | sed -e 's/\,.*//' );
&lt;       fullspace=$($_vgs 2&gt;/dev/null | grep $volumeName | awk -v n=$cnSize '{print $n}' | sed -e 's/\,.*//' );
---
&gt;       freespace=$($_vgs 2&gt;/dev/null | grep $volumeName | awk -v n=$cnFree '{print $n}' | sed -e 's/.$//');
&gt;       fullspace=$($_vgs 2&gt;/dev/null | grep $volumeName | awk -v n=$cnSize '{print $n}' | sed -e 's/.$//');
186c185
&lt;       for (( i=1; i &lt;= novg; i++ )); do
---
&gt;       for (( i=0; i &lt; novg; i++ )); do
</code></pre>

Regards

**Comment by billcarlson** [comment]
Debian, as of version 7+, does not list commas in vgs output.

**Comment by Alpharacks** [comment]
Hi,

We are having some issue on issue on getting issue on the master node.

=
/usr/local/nagios/libexec/check_nrpe -H xxx.xxx.xxx.xx -c check_vg_size
false
No Volumegroup wasn't valid or wasn't found
===

In nagios client it is working.
=
# ./check_vg_size -w 50 -c 20  -a
VG VolGroup WARNING Available space is 42 GB;| VolGroup=42GB;50;20;0;930
=

Please any one help me to resolve it.

**Comment by billcarlson** [comment]
Alpharacks:

Access to volume group information requires privileged access, nrpe typically runs under an account that does not. You'll need to setup sudo configuration for this and add to nrpe.cfg.

Please move this to another issue to continue, this is not relevant to this issue.
